sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t inthrakumarp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true inthrakumarp/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-app"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-351521405801"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY